export enum Country {
    ENGLAND = "England",
    GERMANY = "Germany",
    POLAND = "Poland",
    ITALY = "Italy",
    FRANCE = "France",
    NETHERLANDS = "Netherlands",
    BELGIUM = "Belgium",
    SERBIA = "Serbia",
    BULGARIA = "Bulgaria",
    TURKEY = "Turkey",
    AUSTRALIA = "Australia",
    CANADA = "Canada",
    USA = "USA",
    MEXICO = "Mexico",
    BRAZIL = "Brazil",
    ARGENTINA = "Argentina",
    CHINA = "China",
    JAPAN = "Japan",
    SOUTH_KOREA = "South Korea",
    MONGOLIA = "Mongolia",
    MALAYSIA = "Malaysia"
}
