export enum Hobby {
    TRAVELLING = "Travelling",
    FOOTBALL = "Football",
    TENNIS = "Tennis",
    BASKETBALL = "Basketball",
    VOLLEYBALL = "Volleyball",
    HISTORY = "History",
    BOARD_GAMES = "Board games",
    CLUBBING = "Clubbing",
    LANGUAGE_LEARNING = "Language learning",
    NEW_CUISINES = "New cuisines",
    MOUNTAINS = "Mountains",
    SURFING = "Surfing",
    VIDEO_GAMES = "Video games",
    ART = "Art",
    BOOKS = "Books",
    CAFES = "Cafes",
    DANCING = "Dancing",
    FISHING = "Fishing"
}
