export enum Language {
    ENGLISH = "English",
    SPANISH = "Spanish",
    FRENCH = "French",
    GERMAN = "German",
    DUTCH = "Dutch",
    ITALIAN = "Italian",
    IRISH = "Irish",
    PORTUGUESE = "Portuguese",
    POLISH = "Polish",
    CZECH = "Czech",
    SLOVAK = "Slovak",
    SLOVENIAN = "Slovenian",
    CROAT = "Croat",
    SERBIAN = "Serbian",
    ALBANIAN = "Albanian",
    GREEK = "Greek",
    SWEDISH = "Swedish",
    NORWEGIAN = "Norwegian",
    FINNISH = "Finnish",
    TURKISH = "Turkish",
    RUSSIAN = "Russian",
    ARABIC = "Arabic",
    JAPANESE = "Japanese",
    KOREAN = "Korean",
    SIMPLIFIED_CHINESE = "Simplified Chinese"
}
